[package]
name = "morse_rs"
description = "A simple morse code translator, with the abilty to write to WAV files using Hound."
license = "MIT"
version = "0.1.2"
edition = "2021"

[dependencies]
hound = "3.5.1"
